name: CI

on:
  pull_request:
  push:
    branches:
      - main
    tags-ignore:
      - v*

jobs:
  build:
    name: Code Style, Tests, Documentation
    runs-on: ubuntu-24.04
    env:
      JAVA_OPTS: -Xms2G -Xmx2G -Xss2M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Java 11
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
        with:
          distribution: temurin
          java-version: 11

      - name: Install sbt
        uses: sbt/setup-sbt@6c68d2fe8dfbc0a0534d70101baa2e0420e1a506 # v1.1.9

      - name: Cache Coursier cache
        uses: coursier/cache-action@v6

      - name: "Code style, tests, documentation"
        run: sbt "scalafmtCheckAll; scalafmtSbtCheck; test; doc"
